#!/usr/bin/env bash
# Installing nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Fix permission problems on folder, grant access to ubuntu group Ubuntu 14.04
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
# Index file and start
echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
