#!/usr/bin/env bash
# Setup a redirection to the url /redirect_me

sudo apt update &&
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Fix permission problems on folder, grant access to ubuntu group Ubuntu 14.04
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
# Index file
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
# Edit configuration file? stop the service!
sudo service nginx stop
# Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
# Restart
sudo service nginx restart
