#!/usr/bin/env bash
# Setup a redirection to the url /redirect_me

sudo apt update &&
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
# Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Restart
sudo /etc/init.d/nginx restart
