#!/usr/bin/env bash
# Createa 404 response page

sudo apt update &&
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
# Redirect url
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# 404 Page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404_error.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
# Restart
sudo /etc/init.d/nginx restart
