#!/usr/bin/env bash
# Configure web servers for load balancer - add header

sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "/listen 80 default_server/a \\\t# Header:\n\tadd_header X-Served-By \"$HOSTNAME\";\n" /etc/nginx/sites-available/default
sudo service nginx restart
