#!/usr/bin/env bash
# Configure web servers for load balancer - add header

sudo apt update &&
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
# Permissions
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
sudo chgrp -R ubuntu /var/www/html
sudo chmod -R g+w /var/www/html
# Create Files
echo 'Holberton School' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
# Edit File
sed -i '/listen 80 default_server/a \\t# rewrite:\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a \\t# 404 Page:\n\terror_page 404 /custom_404.html; location = /custom_404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n\t}\n' /etc/nginx/sites-available/default
service nginx start
