#!/usr/bin/env bash
# Configure web servers for load balancer - add header

sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "26i add_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
