#!/usr/bin/env bash
# Configure web servers for load balancer - HAPROXY config

sudo apt update &&
sudo apt-get -y install haproxy
# Backup basic configuration
EPOCH=$(date +%s)
cp /etc/haproxy/haproxy.cfg ./haproxy.$EPOCH.cfg
# Enable HAPROXY
echo "ENABLED=1" >> /etc/default/haproxy
# Write config
cat >> /etc/haproxy/haproxy.cfg << EOF
listen http-in
        bind *:80
        mode http
        balance roundrobin
        server 1201-web-01 52.200.131.229:80 check
        server 1201-web-02 54.146.160.217:80 check
EOF
# Create Files
service haproxy restart
