#!/usr/bin/env bash
# In order for you to set up replication, you’ll need to have a database with at least one table and one row in your primary MySQL server (web-01) to replicate from.

sudo mysql -uroot -p -e "grant select on tyrell_corp.* to 'holberton_user'@'localhost'"
sudo mysql -uroot -p -e "USE tyrell_corp; CREATE TABLE nexus6 ( id int not null auto_increment, name varchar(50) not null, constraint pk_example primary key (id) )"
sudo mysql -uroot -p -e "USE tyrell_corp; INSERT INTO tyrell_corp.nexus6 ( id, name ) VALUES ( null, 'Leon' )"
