#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

mysqldump -u root -p"$1" --all-databases > backup.sql 
tar cfz "$(date +%m-%d-%Y).tar.gz" backup.sql
