#!/usr/bin/env bash
# Make it sweet and short
sudo cat /etc/nginx/sites-available/default | sudo tee /etc/nginx/sites-enabled/default
sudo service nginx start
sudo echo "for real" | sudo tee /run/nginx.pid
