#!/usr/bin/env bash
# We killed our 4-to_infinity_and_beyond process using ctrl+c in the previous
# task, there is actually another way to do this.
var=$(pgrep -f '4-to_infinity_and_beyond')
kill "$var"
