#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
for I in {1..100}
do
	if ((I%3==0 && I%5==0))
	then
		echo "FizzBuzz"
	elif ((I%3==0))
	then
		echo "Fizz"
	elif ((I%5==0))
	then
		echo "Buzz"
	else
		echo $I
	fi
	((I++))
done
