#!/usr/bin/env bash
#A Bash script that displays Holberton School 10 times, but for the 9th
#iteration

I=1
while [ $I -le 10 ]
do
	echo "Holberton School"
	if [ $I -eq 9 ]
	then
		echo "Hi"
	fi
	((I++))
done
